<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net11.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Platforms>AnyCPU;x64;ARM64</Platforms>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="Elysium.Application.Abstractions" Version="$(ElysiumVersion)" />
		<PackageReference Include="Elysium.Platform.Abstractions" Version="$(ElysiumVersion)" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Infinity.Application.Abstractions\Infinity.Application.Abstractions.csproj" />
		<ProjectReference Include="..\Infinity.Platform.Abstractions\Infinity.Platform.Abstractions.csproj" />
	</ItemGroup>
</Project>
