using CommunityToolkit.Mvvm.Messaging;
using Elysium.Application.Abstractions;
using Elysium.Application.DependencyInjection;
using Elysium.Platform.Abstractions;
using Elysium.Platform.Windows;
using Infinity.Application.Abstractions;
using Infinity.Platform.Abstractions;
using Microsoft.Extensions.DependencyInjection;

namespace Infinity.Shell.WinUI;

public class DesktopSettingsModule :
    IModule
{
    public void Register(IServiceCollection services)
    {
        services
            .AddViewFor<VirtualPagesView, IDesktopViewModel, VirtualPagesViewModel>(ServiceLifetime.Transient,
                provider => new VirtualPagesView(),
                provider => new VirtualPagesViewModel(provider,
                    provider.GetRequiredService<IServiceFactory>(),
                    provider.GetRequiredService<IMessenger>(),
                    provider.GetRequiredService<IDisposer>(),
                    provider.GetRequiredService<IDispatcher>(),
                    provider.GetRequiredService<Settings>(),
                    provider.GetRequiredService<IWritableOptions<Settings>>(),
                    config => (int)config.VirtualPagesMode,
                    (config, virtualPagesMode) => config.VirtualPagesMode = (VirtualPagesMode)virtualPagesMode))
            .AddViewFor<VirtualPagesCountView, IDesktopViewModel, VirtualPagesCountViewModel>(ServiceLifetime.Transient,
                provider => new VirtualPagesCountView(),
                provider => new VirtualPagesCountViewModel(provider,
                    provider.GetRequiredService<IServiceFactory>(),
                    provider.GetRequiredService<IMessenger>(),
                    provider.GetRequiredService<IDisposer>(),
                    provider.GetRequiredService<IDispatcher>(),
                    provider.GetRequiredService<Settings>(),
                    provider.GetRequiredService<IWritableOptions<Settings>>(),
                    config => config.VirtualPagesCount,
                    (config, virtualPagesCount) => config.VirtualPagesCount = virtualPagesCount))
            .AddViewFor<ScrollSpeedView, IDesktopViewModel, ScrollSpeedViewModel>(ServiceLifetime.Transient,
                provider => new ScrollSpeedView(),
                provider => new ScrollSpeedViewModel(provider,
                    provider.GetRequiredService<IServiceFactory>(),
                    provider.GetRequiredService<IMessenger>(),
                    provider.GetRequiredService<IDisposer>(),
                    provider.GetRequiredService<IDispatcher>(),
                    provider.GetRequiredService<Settings>(),
                    provider.GetRequiredService<IWritableOptions<Settings>>(),
                    config => (int)config.ScrollSpeed,
                    (config, scrollSpeed) => config.ScrollSpeed = (ScrollSpeed)scrollSpeed))
            .AddViewFor<DragScrollSpeedView, IDesktopViewModel, DragScrollSpeedViewModel>(ServiceLifetime.Transient,
                provider => new DragScrollSpeedView(),
                provider => new DragScrollSpeedViewModel(provider,
                    provider.GetRequiredService<IServiceFactory>(),
                    provider.GetRequiredService<IMessenger>(),
                    provider.GetRequiredService<IDisposer>(),
                    provider.GetRequiredService<IDispatcher>(),
                    provider.GetRequiredService<Settings>(),
                    provider.GetRequiredService<IWritableOptions<Settings>>(),
                    config => (int)config.DragScrollSpeed,
                    (config, dragScrollSpeed) => config.DragScrollSpeed = (DragScrollSpeed)dragScrollSpeed))
            .AddViewFor<ScrollModifierKeyView, IDesktopViewModel, ScrollModifierKeyViewModel>(ServiceLifetime.Transient,
                provider => new ScrollModifierKeyView(),
                provider => new ScrollModifierKeyViewModel(provider,
                    provider.GetRequiredService<IServiceFactory>(),
                    provider.GetRequiredService<IMessenger>(),
                    provider.GetRequiredService<IDisposer>(),
                    provider.GetRequiredService<IDispatcher>(),
                    provider.GetRequiredService<Settings>(),
                    provider.GetRequiredService<IWritableOptions<Settings>>(),
                    config => config.ScrollModifierKeys,
                    (config, scrollModifierKeys) => config.ScrollModifierKeys = scrollModifierKeys!,
                    provider.GetRequiredService<IHotKeysBuilder>(),
                    provider.GetRequiredService<HotKeysBuilderOptions>(),
                    provider.GetRequiredService<IKeyLabelProvider>(),
                    provider.GetRequiredService<ITextLocalizer>()))
            .AddViewFor<DesktopHistoryEnabledView, IDesktopViewModel, DesktopHistoryEnabledViewModel>(ServiceLifetime.Transient,
                provider => new DesktopHistoryEnabledView(),
                provider => new DesktopHistoryEnabledViewModel(provider,
                    provider.GetRequiredService<IServiceFactory>(),
                    provider.GetRequiredService<IMessenger>(),
                    provider.GetRequiredService<IDisposer>(),
                    provider.GetRequiredService<IDispatcher>(),
                    provider.GetRequiredService<Settings>(),
                    provider.GetRequiredService<IWritableOptions<Settings>>(),
                    config => config.DesktopHistoryEnabled,
                    (config, enabled) => config.DesktopHistoryEnabled = enabled))
            .AddViewFor<DesktopHistoryCapacityView, IDesktopViewModel, DesktopHistoryCapacityViewModel>(ServiceLifetime.Transient,
                provider => new DesktopHistoryCapacityView(),
                provider => new DesktopHistoryCapacityViewModel(provider,
                    provider.GetRequiredService<IServiceFactory>(),
                    provider.GetRequiredService<IMessenger>(),
                    provider.GetRequiredService<IDisposer>(),
                    provider.GetRequiredService<IDispatcher>(),
                    provider.GetRequiredService<Settings>(),
                    provider.GetRequiredService<IWritableOptions<Settings>>(),
                    config => config.DesktopHistoryCapacity,
                    (config, capacity) => config.DesktopHistoryCapacity = capacity))
            .AddViewFor<DesktopHistoryBackShortcutView, IDesktopViewModel, DesktopHistoryBackShortcutViewModel>(ServiceLifetime.Transient,
                provider => new DesktopHistoryBackShortcutView(),
                provider => new DesktopHistoryBackShortcutViewModel(provider,
                    provider.GetRequiredService<IServiceFactory>(),
                    provider.GetRequiredService<IMessenger>(),
                    provider.GetRequiredService<IDisposer>(),
                    provider.GetRequiredService<IDispatcher>(),
                    provider.GetRequiredService<Settings>(),
                    provider.GetRequiredService<IWritableOptions<Settings>>(),
                    new HotKeysBuilder(new HotKeysBuilderOptions { KeyCount = 3 }),
                    provider.GetRequiredService<IKeyLabelProvider>(),
                    provider.GetRequiredService<ITextLocalizer>()))
            .AddViewFor<DesktopHistoryForwardShortcutView, IDesktopViewModel, DesktopHistoryForwardShortcutViewModel>(ServiceLifetime.Transient,
                provider => new DesktopHistoryForwardShortcutView(),
                provider => new DesktopHistoryForwardShortcutViewModel(provider,
                    provider.GetRequiredService<IServiceFactory>(),
                    provider.GetRequiredService<IMessenger>(),
                    provider.GetRequiredService<IDisposer>(),
                    provider.GetRequiredService<IDispatcher>(),
                    provider.GetRequiredService<Settings>(),
                    provider.GetRequiredService<IWritableOptions<Settings>>(),
                    new HotKeysBuilder(new HotKeysBuilderOptions { KeyCount = 3 }),
                    provider.GetRequiredService<IKeyLabelProvider>(),
                    provider.GetRequiredService<ITextLocalizer>()))
            .AddViewFor<DesktopHistoryMouseButtonsView, IDesktopViewModel, DesktopHistoryMouseButtonsViewModel>(ServiceLifetime.Transient,
                provider => new DesktopHistoryMouseButtonsView(),
                provider => new DesktopHistoryMouseButtonsViewModel(provider,
                    provider.GetRequiredService<IServiceFactory>(),
                    provider.GetRequiredService<IMessenger>(),
                    provider.GetRequiredService<IDisposer>(),
                    provider.GetRequiredService<IDispatcher>(),
                    provider.GetRequiredService<Settings>(),
                    provider.GetRequiredService<IWritableOptions<Settings>>(),
                    config => config.DesktopHistoryMouseButtonsEnabled,
                    (config, enabled) => config.DesktopHistoryMouseButtonsEnabled = enabled))
            .AddViewFor<DesktopHistoryClearView, IDesktopViewModel, DesktopHistoryClearViewModel>(ServiceLifetime.Transient,
                provider => new DesktopHistoryClearView(),
                provider => new DesktopHistoryClearViewModel(provider,
                    provider.GetRequiredService<IServiceFactory>(),
                    provider.GetRequiredService<IMessenger>(),
                    provider.GetRequiredService<IDisposer>(),
                    provider.GetRequiredService<IDispatcher>(),
                    provider.GetRequiredService<IDesktopNavigationHistory>()))
            .AddViewFor<WindowPeekView, IDesktopViewModel, WindowPeekViewModel>(ServiceLifetime.Transient,
                provider => new WindowPeekView(),
                provider => new WindowPeekViewModel(provider,
                    provider.GetRequiredService<IServiceFactory>(),
                    provider.GetRequiredService<IMessenger>(),
                    provider.GetRequiredService<IDisposer>(),
                    provider.GetRequiredService<IDispatcher>(),
                    provider.GetRequiredService<Settings>(),
                    provider.GetRequiredService<IWritableOptions<Settings>>(),
                    config => config.HideFilteredWindows,
                    (config, hideFilteredWindows) => config.HideFilteredWindows = hideFilteredWindows))
            .AddViewFor<DesktopBlurView, IDesktopViewModel, DesktopBlurViewModel>(ServiceLifetime.Transient,
                provider => new DesktopBlurView(),
                provider => new DesktopBlurViewModel(provider,
                    provider.GetRequiredService<IServiceFactory>(),
                    provider.GetRequiredService<IMessenger>(),
                    provider.GetRequiredService<IDisposer>(),
                    provider.GetRequiredService<IDispatcher>(),
                    provider.GetRequiredService<Settings>(),
                    provider.GetRequiredService<IWritableOptions<Settings>>(),
                    config => config.DesktopBlur,
                    (config, desktopBlur) => config.DesktopBlur = desktopBlur));
    }
}
