<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
		<Platforms>AnyCPU;x64</Platforms>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="Elysium.Application.Abstractions" Version="$(ElysiumVersion)" />
		<PackageReference Include="Elysium.Licensing.Abstractions" Version="$(ElysiumVersion)" />
		<PackageReference Include="Elysium.Platform.Abstractions" Version="$(ElysiumVersion)" />
		<PackageReference Include="Elysium.Presentation" Version="$(ElysiumVersion)" />
		<PackageReference Include="Elysium.Presentation.Abstractions" Version="$(ElysiumVersion)" />
		<PackageReference Include="Elysium.Presentation.DependencyInjection" Version="$(ElysiumVersion)" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.10" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.10" />
		<PackageReference Include="Microsoft.Extensions.Options" Version="10.0.10" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Infinity.Application.Abstractions\Infinity.Application.Abstractions.csproj" />
		<ProjectReference Include="..\Infinity.Platform.Abstractions\Infinity.Platform.Abstractions.csproj" />
	</ItemGroup>
</Project>
