using Infinity.Platform.Abstractions;

namespace Infinity.Platform.Windows;

public class KeyLabelProvider :
    IKeyLabelProvider
{
    public string GetShortLabel(int keyCode) => Shorten(GetFullLabel(keyCode));

    public string Shorten(string fullText)
    {
        return fullText switch
        {
            "Browser Back" => "B Back",
            "Browser Forward" => "B Fwd",
            "Browser Refresh" => "B Ref",
            "Browser Favorites" => "B Fav",
            "Browser Search" => "B Srch",
            "Browser Home" => "B Home",
            "Media Play/Pause" => "Play",
            "Media Previous" => "Prev",
            "Media Next" => "Next",
            "Volume Mute" => "Mute",
            "Volume Down" => "Vol -",
            "Volume Up" => "Vol +",
            "Print Screen" => "PrtSc",
            "Page Up" => "PgUp",
            "Page Down" => "PgDn",
            "Backspace" => "Bksp",
            "Caps Lock" => "Caps",
            "Num Lock" => "Num",
            "Scroll Lock" => "ScrLk",
            "IME Mode Change" => "IME",
            "IME NonConvert" => "IME",
            "IME Convert" => "IME",
            "IME Accept" => "IME",
            "Launch Mail" => "Mail",
            "Launch Media" => "Media",
            "Launch App 1" => "App 1",
            "Launch App 2" => "App 2",
            _ => fullText
        };
    }

    public string GetFullLabel(int keyCode)
    {
        return keyCode switch
        {
            0x01 => "Left Mouse",
            0x02 => "Right Mouse",
            0x03 => "Cancel",
            0x04 => "Middle Mouse",
            0x05 => "XButton 1",
            0x06 => "XButton 2",
            0x08 => "Backspace",
            0x09 => "Tab",
            0x0C => "Clear",
            0x0D => "Enter",
            0x10 => "Shift",
            0x11 => "Ctrl",
            0x12 => "Alt",
            0x13 => "Pause",
            0x14 => "Caps Lock",
            0x15 => "IME Kana",
            0x17 => "IME Junja",
            0x18 => "IME Final",
            0x19 => "IME Hanja",
            0x1B => "Escape",
            0x1C => "IME Convert",
            0x1D => "IME NonConvert",
            0x1E => "IME Accept",
            0x1F => "IME Mode Change",
            0x20 => "Space",
            0x21 => "Page Up",
            0x22 => "Page Down",
            0x23 => "End",
            0x24 => "Home",
            0x25 => "Left",
            0x26 => "Up",
            0x27 => "Right",
            0x28 => "Down",
            0x29 => "Select",
            0x2A => "Print",
            0x2B => "Execute",
            0x2C => "Print Screen",
            0x2D => "Insert",
            0x2E => "Delete",
            0x2F => "Help",
            0x5B => "Win",
            0x5C => "Win",
            0x5D => "Apps",
            0x5F => "Sleep",
            0x60 => "Num 0",
            0x61 => "Num 1",
            0x62 => "Num 2",
            0x63 => "Num 3",
            0x64 => "Num 4",
            0x65 => "Num 5",
            0x66 => "Num 6",
            0x67 => "Num 7",
            0x68 => "Num 8",
            0x69 => "Num 9",
            0x6A => "Num *",
            0x6B => "Num +",
            0x6C => "Separator",
            0x6D => "Num -",
            0x6E => "Num .",
            0x6F => "Num /",
            0x90 => "Num Lock",
            0x91 => "Scroll Lock",
            0xA0 => "Shift",
            0xA1 => "Shift",
            0xA2 => "Ctrl",
            0xA3 => "Ctrl",
            0xA4 => "Alt",
            0xA5 => "Alt",
            0xA6 => "Browser Back",
            0xA7 => "Browser Forward",
            0xA8 => "Browser Refresh",
            0xA9 => "Browser Stop",
            0xAA => "Browser Search",
            0xAB => "Browser Favorites",
            0xAC => "Browser Home",
            0xAD => "Volume Mute",
            0xAE => "Volume Down",
            0xAF => "Volume Up",
            0xB0 => "Media Next",
            0xB1 => "Media Previous",
            0xB2 => "Media Stop",
            0xB3 => "Media Play/Pause",
            0xB4 => "Launch Mail",
            0xB5 => "Launch Media",
            0xB6 => "Launch App 1",
            0xB7 => "Launch App 2",
            0xBA => ";",
            0xBB => "=",
            0xBC => ",",
            0xBD => "-",
            0xBE => ".",
            0xBF => "/",
            0xC0 => "`",
            0xDB => "[",
            0xDC => "\\",
            0xDD => "]",
            0xDE => "'",
            0xE2 => "OEM 102",
            0xE5 => "IME Process",
            0xE7 => "Packet",
            0xF6 => "Attn",
            0xF7 => "CrSel",
            0xF8 => "ExSel",
            0xF9 => "Erase EOF",
            0xFA => "Play",
            0xFB => "Zoom",
            0xFC => "No Name",
            0xFD => "PA1",
            0xFE => "Clear",
            >= 0x30 and <= 0x39 => ((char)keyCode).ToString(),
            >= 0x41 and <= 0x5A => ((char)keyCode).ToString(),
            >= 0x70 and <= 0x87 => $"F{keyCode - 0x6F}",
            _ => $"VK {keyCode}"
        };
    }
}